name: scancode_app
description: Application designed to do a code scan, starting from the consumption of CodeTrace web application endpoints. All the credit for icons and data to said web.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  fonts:
    - family: BalooDa
      fonts:
        - asset: assets/fonts/BalooDa-Regular.ttf